added keys
npmccallum/nixos-sgx pull request #1
Opened 2019-11-21 17:36 UTC by lkatalin

Added my key and Mark's key.

2019-11-21 18:05 UTC, npmccallum requested changes
I think we need this format:

```
users.users = {
  npmccallum = { ... };
  mbestavros = { ... };
  lsturman = { ... };
};
```

Also, I don't think I want to grant you root access. So no `wheel` group.

I'll have to add an sgx group and a udev entry for it.

2019-11-21 18:31 UTC, lkatalin commented
Thanks - let me know if this new version works.

2019-11-21 20:38 UTC, steveeJ commented on configuration.nix
> -  users.mutableUsers = false;
Did you remove this line intentionally?

2019-11-21 20:38 UTC, steveeJ commented on configuration.nix
> +      extraGroups = [ "wheel" ];
should probably also be in the sgx group, and only use wheel privileges for other operations.

2019-11-21 21:51 UTC, lkatalin commented on configuration.nix
> -  users.mutableUsers = false;
No; good catch. : )

2019-11-22 22:07 UTC, npmccallum approved these changes

2019-11-22 22:07 UTC, merged